### PR TITLE
[ENH] Replace Hub with Conversation

### PR DESCRIPTION
**Pull request by fstojanac**
Hi Simon! 

I've encountered a place where the current way of inheriting things (`Im : Hub` and `Channel : Hub`) is a problem. If you use `Conversations.Info` method to get something you know is a `Im` for example, you can't cast it safely to `Im` since `Im` is not inheriting `Conversation`.

An easy way out of this would be to just make `Hub` inherit `Conversation` (they are the same, so it wouldn't have any added properties), but I don't see a reason in keeping `Hub` around at all. 🤔 

Maybe I've missed something obvious and important (I'm using Events API, and haven't looked into RTM in-depth), but I think this PR solves the issue I had mentioned and simplifies how things are inherited and used (namely keeping `Hub` and `Conversation` the same). 🤞

### CODE REVIEW

**Comment by soxtoby** [comment]
Slack doesn't provide a `type` for conversations, so every conversation is deserialized as a `Conversation`. Even if the `Im` class inherits from `Conversation`, you won't be able to cast `Conversation`s to `Im`, because they won't be instances of the `Im` class.

If you're trying to get access to the `User` and `IsUserDeleted` properties, it looks like they just need to be added to `Conversation`.

**Comment by fstojanac** [comment]
Yeah, I've realized the same thing after submitting this... 😅 I'll follow up with a commit soon.

However, do you see a reason to keep `Hub` around?

**Comment by soxtoby** [comment]
The main reason to keep `Hub` is to avoid breaking existing code. For this same reason, I want to avoid renaming things as much as possible.

Additionally, the `Channels`, `Groups`, `Im`, and `Mpim` APIs are a set of legacy APIs that are completely replaced by the new `Conversations` API, so I don't think they should be getting mixed together like this.

I'm going to close this PR, but I'll add the two missing properties to `Conversation` and push up a new release today. It turns out these legacy API endpoints are going to be turned off in November, so I'll need to make a similar change to `SlackBot` eventually, but I want to think about how to do it so it breaks as little code as possible.

**Comment by fstojanac** [comment]
Understood. Thanks for a speedy release and keeping this clean and up to date. 💪

**Pull request closed without merging**
