### PR TITLE
Removed deprecated as_user param in DeleteScheduledMessage

### PR DESCRIPTION
**Pull request by magnusfox**

### CODE REVIEW

**Comment by soxtoby** [comment]
The `as_user` parameter seems to work just fine for me, with both old and new type apps. Might be something specific to your scenario that means it's deprecated?

**Comment by magnusfox** [comment]
> The `as_user` parameter seems to work just fine for me, with both old and new type apps. Might be something specific to your scenario that means it's deprecated?

Not sure what that would be? Anyway, would it be an option to pass the asUser parameter as a nullable to the DeleteScheduledMessage method and add it to the API-call only if it has a value?

**Comment by soxtoby** [comment]
I've made `asUser` nullable in v0.10.18. When null, it shouldn't be included in the request, so hopefully that works for you now.

**Comment by magnusfox** [comment]
@soxtoby Great, thanks!

**Pull request closed without merging**
