### PR TITLE
Upgrade to .NET Standard 2.0.

### PR DESCRIPTION
**Pull request by casperOne**
Updates project libraries to .NET Standard 2.0.

Updates examples to .NET Core 3.1, as 2.x is at end-of-life as per:

https://devblogs.microsoft.com/dotnet/net-core-2-2-will-reach-end-of-life-on-december-23-2019/

Addresses #31 as well as incorporates feedback from #32.

### CODE REVIEW

**Comment by casperOne** [comment]
@soxtoby Was able to get the build started (you were right about gitversion and the branch, thank you).

Trying to figure out how to get MSBuild to use .NET Core 3.1 SDK and not 2.x.

Any insight would be appreciated.

Any objection to using `dotnet build` (I think I can figure out how to get cake to do that).

**Comment by casperOne** [comment]
@soxtoby I've tried rolling back to .NETCoreApp 2.1, but I wasn't able to get it to build still.  Approaches taken:

- Create `global.json` for .NETCoreApp 3.1
- Rolling back references in projects to .NETCoreApp 2.1

Any insight would be appreciated.

**Comment by soxtoby** [comment]
Sorry, this was my fault - I'd overridden the build config in appveyor to try to figure out what was going on with previous PR and forgot to revert my changes 🙇

**Comment by casperOne** [comment]
@soxtoby Thanks!  Will this be pushed to NuGet?

**Comment by soxtoby** [comment]
Soon, yes. Hopefully today or Wednesday. It's a breaking change and I've got some other changes I want to get in with it.

**Pull request merged**
